/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "IfxStm.h"
#include "IfxScuCcu.h"


IfxCpu_syncEvent g_cpuSyncEvent = 0;

/* Declare STM variables */
Ifx_STM *stmSfr;
IfxStm_CompareConfig stmConfig;

/* Define priorities for the ISR */
#define IFX_INTPRIO_STM0_SR0  10

#define STM_TIME_1MS    100000U

void init_led(void);
void init_stm0(void);
void core0_task(void);
void core0_task_1ms(void);
void core0_task_10ms(void);
void core0_task_100ms(void);

/* Interrupt definition */
IFX_INTERRUPT (stm0Sr0ISR, 0, IFX_INTPRIO_STM0_SR0);

/* variables */
uint32 taskCounter = 0;
uint8 task1msFlag, task10msFlag, task100msFlag = 0;

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /* Initialization of GPIO */
    init_led();

    /* Initialization of STM */
    init_stm0();

    /* Initialization of STM */
    while(1)
    {
        core0_task();
    }
}

/* init GPIO port */
void init_led(void)
{
    /* Set GPIO 10.1 and 10.2 as Output */
    IfxPort_setPinModeOutput(&MODULE_P10, 1, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(&MODULE_P10, 2, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

    /* Set GPIO 10.1 and 10.2 as Low (LED Off) */
    IfxPort_setPinLow(&MODULE_P10, 1);
    IfxPort_setPinLow(&MODULE_P10, 2);
}

/* STM Initialization */
void init_stm0(void)
{
    //IfxStm_enableOcdsSuspend(&MODULE_STM0);

    // 중요한 setting 전 interrupt 발생 금지 시키기.
    IfxCpu_disableInterrupts();

    stmSfr = &MODULE_STM0;
    IfxStm_initCompareConfig(&stmConfig);

    // Compaer 값 설정 --> 왜 100000개 tick이 1ms가 될까?
    stmConfig.ticks = STM_TIME_1MS;

    // 인터럽트 우선순위 설정
    stmConfig.triggerPriority = IFX_INTPRIO_STM0_SR0;
    stmConfig.typeOfService = IfxSrc_Tos_cpu0;

    IfxStm_initCompare(stmSfr, &stmConfig);

    // 중요한 setting 종료 후 interrupt 발생 허가 시키기
    IfxCpu_enableInterrupts();
}



void stm0Sr0ISR(void)
{
    IfxStm_clearCompareFlag(stmSfr, stmConfig.comparator);
    IfxStm_increaseCompare(stmSfr, stmConfig.comparator, stmConfig.ticks);

    taskCounter++;

    if((taskCounter % 1) == 0U)
    {
        task1msFlag = 1U;
    }

    if((taskCounter % 10) == 0U)
    {
        task10msFlag = 1U;
    }


    if((taskCounter % 100) == 0U)
    {
        task100msFlag = 1U;
    }
}

/* task */
void core0_task(void)
{
   if(task1msFlag == 1U)
   {
       task1msFlag = 0U;
       core0_task_1ms();
   }
   if(task10msFlag == 1U)
   {
       task10msFlag = 0U;
       core0_task_10ms();
   }
   if(task100msFlag == 1U)
   {
       task100msFlag = 0U;
       core0_task_100ms();
   }
}

void core0_task_1ms(void)
{
    ;

}

void core0_task_10ms(void)
{
    IfxPort_togglePin(&MODULE_P10, 1); // Red LED

}

void core0_task_100ms(void)
{
    IfxPort_togglePin(&MODULE_P10, 2); // Blue LED
}
